name: HyperGCT-py310
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - anaconda
  - bioconda
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pillow
  - scikit-learn
  - setuptools
  - wheel
  - pip
  - pytorch=2.7.0
  - torchvision
  - torchaudio
  - ninja
  - openblas
  - mkl
  - protobuf
  - typing_extensions
  - pip:
      - absl-py
      - addict
      - asttokens
      - attrs
      - backcall
      - blinker
      - cachetools
      - click
      - comm
      - configargparse
      - contourpy
      - cycler
      - dash
      - dash-core-components
      - dash-html-components
      - dash-table
      - decorator
      - easydict
      - executing
      - fastjsonschema
      - flask
      - fonttools
      - fsspec
      - fvcore
      - google-auth
      - google-auth-oauthlib
      - grpcio
      - importlib-metadata
      - importlib-resources
      - iopath
      - ipython
      - ipywidgets
      - itsdangerous
      - jedi
      - joblib
      - jsonschema
      - jsonschema-specifications
      - jupyter-core
      - jupyterlab-widgets
      - kiwisolver
      - markdown
      - matplotlib-inline
      - nbformat
      - nest-asyncio
      - nibabel
      - ninja
      - nvitop
      - oauthlib
      - open3d
      - packaging
      - pandas
      - parso
      - pexpect
      - pickleshare
      - pkgutil-resolve-name
      - platformdirs
      - plotly
      - portalocker
      - prompt-toolkit
      - protobuf
      - psutil
      - ptyprocess
      - pure-eval
      - pyasn1
      - pyasn1-modules
      - pygments
      - pyparsing
      - pyquaternion
      - python-dateutil
      - pytz
      - referencing
      - requests-oauthlib
      - retrying
      - rpds-py
      - rsa
      - scikit-learn
      - scipy
      - six
      - stack-data
      - tabulate
      - tenacity
      - tensorboard
      - tensorboard-data-server
      - tensorboard-plugin-wit
      - tensorboardx
      - termcolor
      - threadpoolctl
      - tqdm
      - traitlets
      - tzdata
      - wcwidth
      - werkzeug
      - widgetsnbextension
      - yacs
      - zipp
